name: Version
on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'hotfix/**'
      - 'develop'

  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Download Dependencies
        run: npm install

      - name: Version Alpha
        if: github.ref == 'refs/heads/develop'
        run: |
          npx version -r minor -p alpha -m '[skip ci] %s'

      - name: Version Beta
        if: contains(github.ref, 'release/') || contains(github.ref, 'hotfix/')
        run: |
          npx version -p beta -m '[skip ci] %s'

      - name: Version
        if: github.ref == 'refs/heads/main'
        run: |
          npx version -m '[skip ci] %s'

      - name: Tag
        run: |
          git push && git push --tags
