name: Version
on:
  push:
    branches:
      - 'main'
      - 'release/**'
      - 'hotfix/**'
      - 'develop'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Download Dependencies
        run: npm install

      - name: Version
        if: ${GITHUB_REF#refs/heads/} == 'main'
        run: |
          echo Version

      - name: Version Beta
        if: contains(${GITHUB_REF#refs/heads/}, 'release/') || contains(${GITHUB_REF#refs/heads/}, 'hotfix/')
        run: |
          echo Version Beta

      - name: Version Alpha
        if: ${GITHUB_REF#refs/heads/} == 'develop'
        run: |
          echo Version Alpha
          echo ${GITHUB_REF#refs/heads/}
